### PR TITLE
Fix issues with `plugin-docusaurus-v3` detecting local mode.

### LINKED ISSUE #728: Docusaurus V3 plugin not working on fresh install
### Describe the bug

First we tried integrating the OSS version of the plugin on the existing solution instead of lunr search plugin but we got an error. To verify that the issue is with the orama plugin we've tried on a fresh docusaurus project and it did not work. We are getting some react errors.
See the image below:
image

[Error link](https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=)

When we run the website in development mode using: `npm run start` We get a following error which describes more the minified issue:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `OramaSearchWithDocs`.
```
Thanks for taking your time!

### To Reproduce

1. Initialize fresh docusaurus project. It will create a docusaurus **3.4.0** site
2. Build the website, to verify that docusaurus works. It works.
3. Clear the build and cache folders
4. Install orama docusaurus V3 plugin
5. Add the plugin to docusaurus.config.ts
6. Run `npm run build`
7. Run `npm run serve`

### Expected behavior

Site is built and docusaurus website is rendered with search box.

### Environment Info

```bash
OS: Windows 11
Node: v20.10.0
Orama Plugin Version: 2.0.19
Docusaurus: 3.4.0
```

### Affected areas

Initialization, Search

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by madlitz**
Fixes #728. 

Now on a fresh docusaurus install running `npm run build` then `npm run start` or `npm run serve` should display results correctly.

### CODE REVIEW

File: packages/plugin-docusaurus-v3/src/index.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export default function OramaPluginDocusaurus(
     },
 
     async allContentLoaded({ actions, allContent }) {
-      const isDevelopment = process.env.NODE_ENV === 'development' || !options.cloud?.oramaCloudAPIKey
+      const isDevelopment = process.env.NODE_ENV === 'development' || (options.cloud && !options.cloud?.oramaCloudAPIKey)
```
Comment (micheleriva) [inline packages/plugin-docusaurus-v3/src/index.ts:61]: this could be `!(options?.cloud?.oramaCloudAPIKey)` I think

**Comment by Eomm** [comment]
Can I help to get this fix shipped?

**Comment by jeevanjoseph** [comment]
Can we get this fixed and merged ? I'm also getting 
`Error: ENOENT: no such file or directory, open ... /.docusaurus/orama-search-index-current.json.gz` when trying to use the plugin.

**Comment by HenrikStanley** [comment]
> Can we get this fixed and merged ? I'm also getting `Error: ENOENT: no such file or directory, open ... /.docusaurus/orama-search-index-current.json.gz` when trying to use the plugin.

Experiencing the exact same error here.

**Comment by raiindev** [comment]
@HenrikStanley @jeevanjoseph 
Hey guys, the error mentioned above has been fixed in this [PR](https://github.com/askorama/orama/pull/790).
